require("plugins/vim-plug")

require("plugins/alpha")
require("plugins/coc")
require("plugins/enable_hardtime")
require("plugins/leader")
require("plugins/merge_tool")
require("plugins/miscellaneous")
require("plugins/neoformat")
require("plugins/nerdtree")
