import = [
  # uncomment the flavour you want below:
   "~/.config/alacritty/catpuccin/catppuccin-latte.toml"
  # "~/.config/alacritty/catpuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catpuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catpuccin/catppuccin-mocha.toml"
]

# Paramètres de la police
[font]
normal.family = "BigBlueTermPlus Nerd Font Mono"
size = 15.0

# Paramètres de la fenêtre
[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "full"  # Choix entre "none", "normal", "full"

