# Best practices RTFM !!!!
map ctrl+shift+f1 show_kitty_doc overview

# Font config 
font_family        JetBrainsMono Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
background_opacity 0.9
font_size 15.0

# Miscellaneous
window_padding_width 5
confirm_os_window_close 0
enable_audio_bell no
map ctrl+shift+u kitten unicode_input
cursor_trail 3
cursor_trail_decay 0.1 0.4

# Theme
include rose-pine.conf

# Keyboard Shortcut I'm VIM Addict btw
kitty_mod ctrl+shift

action_alias launch_tab launch --type=tab --cwd=current

map f1 launch_tab nvim
map kitty_mod+k scroll_line_up
map kitty_mod+j scroll_line_down

# Window management
map kitty_mode+enter new_window
map ctrl+alt+enter launch --cwd=current
map ctrl+alt+h previous_window
map ctrl+alt+l next_window

# Tab management
map kitty_mod+l next_tab
map kitty_mod+h previous_tab

# Layout management
map ctrl+alt+c next_layout
map ctrl+alt+t goto_layout tall
map ctrl+alt+s goto_layout stack
